server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa?serverTimezone=Asia/Seoul
    username: spring
    password: spring
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    database: mysql
  servlet:
    multipart:
      max-file-size: 10MB # 1개의 파일의 최대 사이즈
      max-request-size: 20MB # 전체 요청의 최대 사이즈

logging.level:
  org.hibernate.SQL: debug

# swagger setting
springdoc:
  swagger-ui:
    path:

jwt:
  secret:

# 업로드 파일 저장 경로
upload:
  path:
